derive_seed request
holochain/lair pull request #110
Opened 2023-02-08 23:21 UTC by maackle

2023-02-08 23:55 UTC, maackle commented on crates/lair_keystore_api/src/lair_client.rs
> +        // ) -> impl Future<Output = LairResult<SeedInfo>> + 'static + Send {
sorry I'll change this back :innocent:

2023-02-09 17:37 UTC, neonphog commented on crates/lair_keystore_api/src/lair_server/priv_api.rs
> +            let limits = PwHashLimits::current();
This call must move up out of the `async move`. If there are any awaits above it, there's a chance the original limits will no longer be in context.

2023-02-09 17:38 UTC, neonphog commented on crates/lair_keystore_api/src/lair_client.rs
> +    #[warn(warnings)]
```suggestion
```

2023-02-09 17:39 UTC, neonphog commented on crates/lair_keystore_api/src/lair_server/priv_api.rs
> +            let limits = PwHashLimits::current();
aw, crud. it's even worse than that. I think you need to move it outside the `async move` in the main public function, and then pass it into here.

2023-02-09 17:43 UTC, neonphog commented on crates/lair_keystore_api/src/lair_api/derive_seed.rs
> +    /// 2nd derivation of the 3rd derivation of the 1st derivation of the source seed.
```suggestion
    /// For instance, [99, 1, 42] would specify that the destination seed is the
    /// 42nd derivation of the 1st derivation of the 99th derivation of the source seed.
```

2023-02-09 17:44 UTC, neonphog commented on crates/lair_keystore_api/src/lair_api/derive_seed.rs
> +    /// The seed info associated with this seed.
```suggestion
    /// The seed info associated with the newly derived seed.
```

2023-02-09 17:47 UTC, neonphog commented on crates/lair_keystore_api/src/lair_api/derive_seed.rs
> +    /// 2nd derivation of the 3rd derivation of the 1st derivation of the source seed.
oh, i see, you were trying to indicate the zero-based-ness of it. I just thought you got the numbers wrong : )

Well, I'll leave my comment up. I'm not sure we need to be pedantic about the ordinality. Feel free to take or leave this.

2023-02-09 17:49 UTC, neonphog requested changes
Couple change requests, but looking good :+1:

2023-02-10 16:21 UTC, neonphog commented on crates/lair_keystore_api/src/lair_server/priv_api.rs
> +            let limits = PwHashLimits::current();
Yeah, use new_seed as a template. The [limits are captured at the top](https://github.com/holochain/lair/blob/a4fa49a2b8dcebe5e784ed44d2c22d6044a8abdc/crates/lair_keystore_api/src/lair_client.rs#L189) and then [forwarded to the server](https://github.com/holochain/lair/blob/a4fa49a2b8dcebe5e784ed44d2c22d6044a8abdc/crates/lair_keystore_api/src/lair_client.rs#L206-L207) in the request.

2023-02-10 20:45 UTC, neonphog commented on crates/lair_keystore_api/src/lair_server/priv_api.rs
> +                *b"IdnSecKy",
Whoops, sorry I missed this earlier, this has to match the seed bundle spec.

```suggestion
                *b"SeedBndl",
```

2023-02-10 20:48 UTC, neonphog commented on crates/lair_keystore_api/src/lair_server/priv_api.rs
> +                        src_seed_info.exportable,
... someday we'll probably want to be able to change the exportable and limits when deriving... but out of scope until we have an actual need for it : )

2023-02-10 20:48 UTC, neonphog requested changes
Sorry I missed the context bytes needing to match. After that, this looks good to go.

2023-02-14 17:54 UTC, neonphog approved these changes

2023-02-14 18:07 UTC, merged