fix: use absolute path for unix socket in connection_url
holochain/lair pull request #117
Opened 2023-09-05 20:52 UTC by mattyg

When creating a new lair config on unix, ensure the param `connection_url` uses an absolute path to the unix socket.

This resolves an issue where `Conductor::builder().build()` panics when passing in `None`, or a relative path for the config option `keystore.lair_root`.

2023-09-06 16:30 UTC, neonphog commented on crates/lair_keystore_api/src/config.rs
> +                let mut con_path = root_path.clone().canonicalize().unwrap();
Please switch to using [dunce::canonicalize](https://docs.rs/dunce/latest/dunce/fn.canonicalize.html). I know this is a non-windows code path, but sometimes code gets copied and the std canonicalize is a big no-no on windows.

2023-09-06 16:48 UTC, neonphog commented
It looks like there are [some fake paths in tests](https://github.com/holochain/lair/blob/9d284d0691ce43780d10130e09f2adc596577d63/crates/lair_keystore_api/src/config.rs#L325) that now break with the canonicalize. Perhaps you can switch them to point directly at the root (`/`) which should always exist an successfully canonicalize?

2023-09-06 16:51 UTC, neonphog commented on crates/lair_keystore_api/tests/config.rs
> +    let _ = create_dir("./config-root-path-test");
ditto `tempfile::tempdir()`

2023-09-06 16:52 UTC, neonphog requested changes
Thanks for doing this! The logic is perfect, just some minor change requests. I swear there was actually an outstanding issue laying around for fixing this, but I can't seem to find it.

2023-09-08 12:07 UTC, abe-njama commented
> Thanks for doing this! The logic is perfect, just some minor change requests. I swear there was actually an outstanding issue laying around for fixing this, but I can't seem to find it.

@neonphog could it be [this](https://www51.v1host.com/Holo/story.mvc/Summary?oidToken=Story%3a36699)?

2023-09-08 15:16 UTC, neonphog commented
@abe

> @neonphog could it be [this](https://www51.v1host.com/Holo/story.mvc/Summary?oidToken=Story%3a36699)?

No, what I'm remembering was a github issue. @Connoropolous do you remember? I feel like you were involved with it.

2023-09-08 15:17 UTC, neonphog approved these changes
nice, thanks!

2023-09-08 17:42 UTC, Connoropolous commented
Yeah it was #103

https://github.com/holochain/lair/issues/103

2023-09-08 18:16 UTC, neonphog commented
> Yeah it was #103
> 
> #103

Ah, awesome thanks. Yeah, it was fixed by documentation, now it'll be actually fixed : )

2023-09-08 18:37 UTC, merged